# Generated by Django 2.0 on 2021-06-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cutomeroreder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutomeroreder',
            name='productName',
        ),
    ]
